{"uuid": "b7d3aa9a-cbcb-4c15-931b-eb5f4ee582ce", "children": ["3f17edfc-2b2e-4104-9845-6f78291b8dff"], "befores": [{"name": "browser", "status": "passed", "start": 1737373016721, "stop": 1737373026665}], "afters": [{"name": "browser::0", "status": "broken", "statusDetails": {"message": "asyncio.exceptions.InvalidStateError: invalid state\n", "trace": "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\project_kicb\\ProdWeb\\conftest.py\", line 8, in browser\n    with sync_playwright() as playwright:\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\playwright\\sync_api\\_context_manager.py\", line 90, in __exit__\n    self._connection.stop_sync()\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 280, in stop_sync\n    self.cleanup()\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 297, in cleanup\n    callback.future.set_exception(self._closed_error)\n"}, "start": 1737373028154, "stop": 1737373028309}], "start": 1737373016721, "stop": 1737373028309}